[package]
name = "hyprquery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.24", features = ["derive"] }
color-eyre = "0.6.2"
hyprland = "0.3.9"
serde_json = "1.0.105"
